# Generated by Django 2.2.4 on 2021-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nac', models.DateField()),
                ('run', models.CharField(max_length=50)),
                ('direccion', models.CharField(default='Chile', max_length=50)),
                ('remitente', models.CharField(max_length=50)),
            ],
        ),
    ]
